In [1]:
#importing Libraries

import pandas as pd
import numpy as np

# Loading Sales,Products,Factories,Targets,Data dictionariess datasets

sales = pd.read_csv('Candy_Sales.csv')
products = pd.read_csv('Candy_Products.csv')
factories = pd.read_csv('Candy_Factories.csv')
targets = pd.read_csv('Candy_Targets.csv')
data_dict = pd.read_csv('candy_distributor_data_dictionary.csv')

In [7]:
# Converting dates in sales to change Date in string format to datetime datatype.
sales['Order Date'] = pd.to_datetime(sales['Order Date'])
sales['Ship Date'] = pd.to_datetime(sales['Ship Date'])
print(sales['Order Date'])
print(sales['Ship Date'])

0       2021-03-31
1       2021-03-31
2       2021-09-15
3       2021-09-15
4       2022-10-04
           ...
10189   2023-04-03
10190   2023-05-05
10191   2023-07-08
10192   2023-07-08
10193   2024-06-11
Name: Order Date, Length: 10194, dtype: datetime64[ns]
0       2026-09-26
1       2026-09-26
2       2027-03-13
3       2027-03-13
4       2028-03-29
           ...
10189   2028-09-29
10190   2028-10-29
10191   2028-12-28
10192   2028-12-28
10193   2029-12-05
Name: Ship Date, Length: 10194, dtype: datetime64[ns]

In [8]:
# Adding derived columns like Year,Profit Margin.
sales['Year'] = sales['Order Date'].dt.year
sales['Profit Margin'] = (sales['Gross Profit'] / sales['Sales']) * 100

In [9]:
# Checking for duplicates and missing values (none found).
sales.drop_duplicates(inplace=True)  
print(sales.isnull().sum())  #Returns 0 if null values are not found.
factories.drop_duplicates(inplace=True)
print(factories.isnull().sum())
targets.drop_duplicates(inplace=True)
print(targets.isnull().sum())
products.drop_duplicates(inplace=True)
print(products.isnull().sum())

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
Year              0
Profit Margin     0
dtype: int64
Factory      0
Latitude     0
Longitude    0
dtype: int64
Division    0
Target      0
dtype: int64
Division        0
Product Name    0
Factory         0
Product ID      0
Unit Price      0
Unit Cost       0
dtype: int64

In [10]:
# Mergeing datasets sales,targets,products,factories for analysis.
# Creating Candy_master_table 
Candy_master_table= pd.merge(sales, products, on=['Product ID', 'Product Name', 'Division'], how='left')
Candy_master_table = pd.merge(Candy_master_table, factories, left_on='Factory', right_on='Factory', how='left')
Candy_master_table= pd.merge(Candy_master_table, targets, on='Division', how='left')

In [11]:
#Quick Preview of Candy_master_table.
print(Candy_master_table.head())
print(Candy_master_table.describe())
print(Candy_master_table.info())

   Row ID                      Order ID Order Date  Ship Date       Ship Mode  \
0     282  US-2021-128055-CHO-TRI-54000 2021-03-31 2026-09-26  Standard Class
1     288  US-2021-128055-CHO-SCR-58000 2021-03-31 2026-09-26  Standard Class
2    1132  US-2021-138100-CHO-FUD-51000 2021-09-15 2027-03-13  Standard Class
3    1133  US-2021-138100-CHO-MIL-31000 2021-09-15 2027-03-13  Standard Class
4    3396  US-2022-121391-CHO-MIL-31000 2022-10-04 2028-03-29     First Class

   Customer ID Country/Region           City State/Province Postal Code  ...  \
0       128055  United States  San Francisco     California       94122  ...
1       128055  United States  San Francisco     California       94122  ...
2       138100  United States  New York City       New York       10011  ...
3       138100  United States  New York City       New York       10011  ...
4       121391  United States  San Francisco     California       94109  ...

  Gross Profit  Cost  Year Profit Margin          Factory  Unit Price  \
0         4.90  2.60  2021     65.333333  Wicked Choccy's        3.75
1         5.00  2.20  2021     69.444444    Lot's O' Nuts        3.60
2         4.80  2.40  2021     66.666667    Lot's O' Nuts        3.60
3         6.33  3.42  2021     64.923077  Wicked Choccy's        3.25
4         4.22  2.28  2022     64.923077  Wicked Choccy's        3.25

   Unit Cost   Latitude   Longitude  Target
0       1.30  32.076176  -81.088371   27000
1       1.10  32.881893 -111.768036   27000
2       1.20  32.881893 -111.768036   27000
3       1.14  32.076176  -81.088371   27000
4       1.14  32.076176  -81.088371   27000

[5 rows x 26 columns]
             Row ID                     Order Date  \
count  10194.000000                          10194
mean    5097.500000  2023-04-30 00:15:40.788699392
min        1.000000            2021-01-03 00:00:00
25%     2549.250000            2022-05-14 00:00:00
50%     5097.500000            2023-06-25 00:00:00
75%     7645.750000            2024-05-14 00:00:00
max    10194.000000            2024-12-30 00:00:00
std     2942.898656                            NaN

                           Ship Date    Customer ID         Sales  \
count                          10194   10194.000000  10194.000000
mean   2028-10-23 23:20:43.790465024  134468.961154     13.908537
min              2026-06-30 00:00:00  100006.000000      1.250000
25%              2027-11-09 00:00:00  117212.000000      7.200000
50%              2028-12-18 00:00:00  133550.000000     10.800000
75%              2029-11-08 00:00:00  152051.000000     18.000000
max              2030-06-28 00:00:00  192314.000000    260.000000
std                              NaN   20231.483007     11.341020

              Units  Gross Profit          Cost          Year  Profit Margin  \
count  10194.000000  10194.000000  10194.000000  10194.000000   10194.000000
mean       3.791838      9.166451      4.742087   2022.720129      66.514045
min        1.000000      0.250000      0.600000   2021.000000       7.692308
25%        2.000000      4.900000      2.400000   2022.000000      65.333333
50%        3.000000      7.470000      3.600000   2023.000000      66.666667
75%        5.000000     12.250000      5.700000   2024.000000      69.444444
max       14.000000    130.000000    130.000000   2024.000000      80.000000
std        2.228317      6.643740      5.061647      1.125611       6.721012

         Unit Price     Unit Cost      Latitude     Longitude        Target
count  10188.000000  10188.000000  10188.000000  10188.000000  10194.000000
mean       3.654201      1.241567     32.798276    -98.558038  26223.072396
min        1.250000      0.600000     32.076176   -111.768036   3000.000000
25%        3.490000      1.100000     32.076176   -111.768036  27000.000000
50%        3.600000      1.140000     32.881893   -111.768036  27000.000000
75%        3.600000      1.200000     32.881893    -81.088371  27000.000000
max       20.000000     10.000000     48.119140    -81.088371  27000.000000
std        1.612348      0.871857      1.576227     14.966377   4180.827958
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
 18  Year            10194 non-null  int32
 19  Profit Margin   10194 non-null  float64
 20  Factory         10188 non-null  object
 21  Unit Price      10188 non-null  float64
 22  Unit Cost       10188 non-null  float64
 23  Latitude        10188 non-null  float64
 24  Longitude       10188 non-null  float64
 25  Target          10194 non-null  int64
dtypes: datetime64[ns](2), float64(8), int32(1), int64(4), object(11)
memory usage: 2.0+ MB
None

In [7]:
Candy_master_table.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
Year              0
Profit Margin     0
Factory           6
Unit Price        6
Unit Cost         6
Latitude          6
Longitude         6
Target            0
dtype: int64

In [8]:
#Numeric Statistics of Candy_master_table.
Candy_master_table.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Gross Profit,Cost,Year,Profit Margin,Factory,Unit Price,Unit Cost,Latitude,Longitude,Target
count,10194.000000,10194,10194,10194,10194,10194.000000,10194,10194,10194,10194,...,10194.000000,10194.000000,10194.000000,10194.000000,10188,10188.000000,10188.000000,10188.000000,10188.000000,10194.000000
unique,NaN,8549,NaN,NaN,4,NaN,2,542,59,654,...,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN
top,NaN,US-2024-157987-CHO-NUT-13000,NaN,NaN,Standard Class,NaN,United States,New York City,California,10035,...,NaN,NaN,NaN,NaN,Lot's O' Nuts,NaN,NaN,NaN,NaN,NaN
freq,NaN,5,NaN,NaN,6120,NaN,9994,915,2001,263,...,NaN,NaN,NaN,NaN,5692,NaN,NaN,NaN,NaN,NaN
mean,5097.500000,NaN,2023-04-30 00:15:40.788699392,2028-10-23 23:20:43.790465024,NaN,134468.961154,NaN,NaN,NaN,NaN,...,9.166451,4.742087,2022.720129,66.514045,NaN,3.654201,1.241567,32.798276,-98.558038,26223.072396
min,1.000000,NaN,2021-01-03 00:00:00,2026-06-30 00:00:00,NaN,100006.000000,NaN,NaN,NaN,NaN,...,0.250000,0.600000,2021.000000,7.692308,NaN,1.250000,0.600000,32.076176,-111.768036,3000.000000
25%,2549.250000,NaN,2022-05-14 00:00:00,2027-11-09 00:00:00,NaN,117212.000000,NaN,NaN,NaN,NaN,...,4.900000,2.400000,2022.000000,65.333333,NaN,3.490000,1.100000,32.076176,-111.768036,27000.000000
50%,5097.500000,NaN,2023-06-25 00:00:00,2028-12-18 00:00:00,NaN,133550.000000,NaN,NaN,NaN,NaN,...,7.470000,3.600000,2023.000000,66.666667,NaN,3.600000,1.140000,32.881893,-111.768036,27000.000000
75%,7645.750000,NaN,2024-05-14 00:00:00,2029-11-08 00:00:00,NaN,152051.000000,NaN,NaN,NaN,NaN,...,12.250000,5.700000,2024.000000,69.444444,NaN,3.600000,1.200000,32.881893,-81.088371,27000.000000
max,10194.000000,NaN,2024-12-30 00:00:00,2030-06-28 00:00:00,NaN,192314.000000,NaN,NaN,NaN,NaN,...,130.000000,130.000000,2024.000000,80.000000,NaN,20.000000,10.000000,48.119140,-81.088371,27000.000000
std,2942.898656,NaN,NaN,NaN,NaN,20231.483007,NaN,NaN,NaN,NaN,...,6.643740,5.061647,1.125611,6.721012,NaN,1.612348,0.871857,1.576227,14.966377,4180.827958

In [9]:
#Removing null values in Candy_master_table.
Candy_master_table.dropna(inplace=True)

In [10]:
print(Candy_master_table.head())

   Row ID                      Order ID Order Date  Ship Date       Ship Mode  \
0     282  US-2021-128055-CHO-TRI-54000 2021-03-31 2026-09-26  Standard Class
1     288  US-2021-128055-CHO-SCR-58000 2021-03-31 2026-09-26  Standard Class
2    1132  US-2021-138100-CHO-FUD-51000 2021-09-15 2027-03-13  Standard Class
3    1133  US-2021-138100-CHO-MIL-31000 2021-09-15 2027-03-13  Standard Class
4    3396  US-2022-121391-CHO-MIL-31000 2022-10-04 2028-03-29     First Class

   Customer ID Country/Region           City State/Province Postal Code  ...  \
0       128055  United States  San Francisco     California       94122  ...
1       128055  United States  San Francisco     California       94122  ...
2       138100  United States  New York City       New York       10011  ...
3       138100  United States  New York City       New York       10011  ...
4       121391  United States  San Francisco     California       94109  ...

  Gross Profit  Cost  Year Profit Margin          Factory  Unit Price  \
0         4.90  2.60  2021     65.333333  Wicked Choccy's        3.75
1         5.00  2.20  2021     69.444444    Lot's O' Nuts        3.60
2         4.80  2.40  2021     66.666667    Lot's O' Nuts        3.60
3         6.33  3.42  2021     64.923077  Wicked Choccy's        3.25
4         4.22  2.28  2022     64.923077  Wicked Choccy's        3.25

   Unit Cost   Latitude   Longitude  Target
0       1.30  32.076176  -81.088371   27000
1       1.10  32.881893 -111.768036   27000
2       1.20  32.881893 -111.768036   27000
3       1.14  32.076176  -81.088371   27000
4       1.14  32.076176  -81.088371   27000

[5 rows x 26 columns]

In [12]:
#Creating new Master table csv file and reading the csv file.

Candy_master_table.to_csv('Candy_master_dataset.csv', index=False)
df=pd.read_csv('Candy_master_dataset.csv')

PermissionError: [Errno 13] Permission denied: 'Candy_master_dataset.csv'

In [14]:
#Modification of columns easier to anlyse in MySql .
df=pd.read_csv('Candy_master_dataset.csv')
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country/region', 'city', 'state/province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost', 'year', 'profit_margin',
       'factory', 'unit_price', 'unit_cost', 'latitude', 'longitude',
       'target'],
      dtype='object')

In [15]:
# Validate data integrity (e.g., unit price consistency)
df['calc_unit_price'] = df['sales'] / df['units']
df['calc_unit_cost'] = df['cost'] / df['units']

In [16]:
print(df.head())

   row_id                      order_id  order_date   ship_date  \
0     282  US-2021-128055-CHO-TRI-54000  2021-03-31  2026-09-26
1     288  US-2021-128055-CHO-SCR-58000  2021-03-31  2026-09-26
2    1132  US-2021-138100-CHO-FUD-51000  2021-09-15  2027-03-13
3    1133  US-2021-138100-CHO-MIL-31000  2021-09-15  2027-03-13
4    3396  US-2022-121391-CHO-MIL-31000  2022-10-04  2028-03-29

        ship_mode  customer_id country/region           city state/province  \
0  Standard Class       128055  United States  San Francisco     California
1  Standard Class       128055  United States  San Francisco     California
2  Standard Class       138100  United States  New York City       New York
3  Standard Class       138100  United States  New York City       New York
4     First Class       121391  United States  San Francisco     California

  postal_code  ...  year profit_margin          factory unit_price  unit_cost  \
0       94122  ...  2021     65.333333  Wicked Choccy's       3.75       1.30
1       94122  ...  2021     69.444444    Lot's O' Nuts       3.60       1.10
2       10011  ...  2021     66.666667    Lot's O' Nuts       3.60       1.20
3       10011  ...  2021     64.923077  Wicked Choccy's       3.25       1.14
4       94109  ...  2022     64.923077  Wicked Choccy's       3.25       1.14

    latitude   longitude  target  calc_unit_price  calc_unit_cost
0  32.076176  -81.088371   27000             3.75            1.30
1  32.881893 -111.768036   27000             3.60            1.10
2  32.881893 -111.768036   27000             3.60            1.20
3  32.076176  -81.088371   27000             3.25            1.14
4  32.076176  -81.088371   27000             3.25            1.14

[5 rows x 28 columns]

In [7]:
import pandas as pd 
import numpy as np
df=pd.read_csv('Candy_master_file.csv')
#(df.info)
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country/region', 'city', 'state/province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost', 'year', 'profit_margin',
       'factory', 'unit_price', 'unit_cost', 'latitude', 'longitude', 'target',
       'calc_unit_price', 'calc_unit_cost'],
      dtype='object')

In [5]:
pip install pymysql sqlalchamey

Requirement already satisfied: pymysql in c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlalchamey (from versions: none)
ERROR: No matching distribution found for sqlalchamey

In [7]:
from sqlalchemy import create_engine
#Mysql connections.
username = "root"      
password = "1234567890"  
host = "localhost"
port = "3306"
database="candy_trend_analysis"
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
#engine = create_engine("mysql+pymysql://username:password@localhost:3306/candy_trend_analysis")
#Writing Daraframe to MySQL
table_name="candy_ds"
df.to_sql(table_name,engine,index=False)
#Reading back sample
pd.read_sql("SELECT * FROM candy_ds LIMIT 5;",engine)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,country/region,city,state/province,postal_code,...,year,profit_margin,factory,unit_price,unit_cost,latitude,longitude,target,calc_unit_price,calc_unit_cost
0,282,US-2021-128055-CHO-TRI-54000,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,94122,...,2021,65.333333,Wicked Choccy's,3.75,1.30,32.076176,-81.088371,27000,3.75,1.30
1,288,US-2021-128055-CHO-SCR-58000,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,94122,...,2021,69.444444,Lot's O' Nuts,3.60,1.10,32.881893,-111.768036,27000,3.60,1.10
2,1132,US-2021-138100-CHO-FUD-51000,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,10011,...,2021,66.666667,Lot's O' Nuts,3.60,1.20,32.881893,-111.768036,27000,3.60,1.20
3,1133,US-2021-138100-CHO-MIL-31000,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,10011,...,2021,64.923077,Wicked Choccy's,3.25,1.14,32.076176,-81.088371,27000,3.25,1.14
4,3396,US-2022-121391-CHO-MIL-31000,2022-10-04,2028-03-29,First Class,121391,United States,San Francisco,California,94109,...,2022,64.923077,Wicked Choccy's,3.25,1.14,32.076176,-81.088371,27000,3.25,1.14